[package]
name = "wtui"
version = "0.1.0"
authors = ["Valentin271"]
license = "MIT"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
clipboard = "0.5.0"
ratatui = "0.28.1"

[profile.release]
strip = true
